# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 75ecc8356db8261ff3d521ad00454d5f9d6dd6289176a9b280d96542d3ccac92d8e0a8eb89107f8c42138336377018c205c20035934bb4387a276fc256eed0a3

test:
  secret_key_base: 33070f76b93d5eced974bde3d06cd365336357b72ada4deca0e2caedf393cd8188af78be8ac6cf39a898fad3cddbf84f5f48aaf3ca3924893a9c7566525a5691

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
