# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a90c1b4436ace79d1dfae29c5ebe6937117453b8ff13bbab8e4ebdbab423958e1c5aeb20c51325718112642081cbddf6d1433f1938c552ac59ebdcf823bd4105

test:
  secret_key_base: 2fe786d31ee53d1e7633bb5372eeefbb637a77e3aa5f9c10374ff13387a475470b4125255adceb5792b8dc3e5ca6128fb79ec340157b600529da86543d22f341

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
